// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Primary content in *HomeHero → Default → Primary*
 */
export interface HomeHeroSliceDefaultPrimary {
  /**
   * Hero Heading field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Main headline in the hero
   * - **API ID Path**: home_hero.default.primary.hero_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_heading: prismic.KeyTextField;

  /**
   * Hero copy intro field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Copy intro in the hero component.
   * - **API ID Path**: home_hero.default.primary.hero_copy_intro
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_copy_intro: prismic.KeyTextField;

  /**
   * Hero Mobile Video field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Mobile hero background video
   * - **API ID Path**: home_hero.default.primary.hero_mobile_video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_mobile_video: prismic.LinkToMediaField;

  /**
   * Hero Desktop Video field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Desktop hero background video
   * - **API ID Path**: home_hero.default.primary.hero_desktop_video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_desktop_video: prismic.LinkToMediaField;
}

/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeHero*
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;

/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: HomeHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSlice = prismic.SharedSlice<
  "home_hero",
  HomeHeroSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      HomeHeroSlice,
      HomeHeroSliceDefaultPrimary,
      HomeHeroSliceVariation,
      HomeHeroSliceDefault,
    };
  }
}
